[project]
name = "formation-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jacquesarnaud", email = "jaarnaud4@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
formation-api = "formation_api:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
